polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)

pybursa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from pybursa import views
from django.views.generic import TemplateView
from feedbacks.views import FeedbackView



urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(),name='index'),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^students/', include('students.urls', namespace='students')),
    url(r'^contact/', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^quadratic/',include('quadratic.urls')),
    url(r'^coaches/',include('coaches.urls',namespace='coaches')),
    url(r'^feedback/', FeedbackView.as_view(), name = "feedback"),
)

students/urls.py
from django.conf.urls import patterns, url
from students import views

urlpatterns = patterns('',
    url(r'^$', views.StudentListView.as_view(), name='list_view'),
    url(r'^(?P<pk>\d+)/$', views.StudentDetailView.as_view(), name='detail'),
    url(r'^add/$', views.StudentCreateView.as_view(), name='add'),
    url(r'^remove/(?P<pk>\d+)/$', views.StudentDeleteView.as_view(), name='remove'),
    url(r'^edit/(?P<pk>\d+)/$', views.StudentUpdateView.as_view(), name='edit'),
)

students/models.py
from django.db import models
from django.core.urlresolvers import reverse
from courses.models import Course

class Student(models.Model):
  name = models.CharField( max_length=255)
  surname = models.CharField(max_length=255)
  date_of_birth = models.DateField()
  email = models.EmailField()
  phone = models.CharField(max_length=15)
  address = models.CharField(max_length=255)
  skype = models.CharField(max_length=100)
  courses = models.ManyToManyField(Course)

  def __unicode__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('students:list_view')

students/forms.py
# -*- coding: utf-8 -*-
from django import forms
from students.models import Student


class StudentModelForm(forms.ModelForm):
  class Meta:
    model = Student
    

students/views.py
# -*- coding: utf-8 -*-
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render,redirect
from students.models import Student
from courses.models import Course
from students.forms import StudentModelForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView

import logging
logger = logging.getLogger(__name__)

class StudentDetailView(DetailView):
  model = Student
  def get_context_data(self, **kwargs):
    logger.debug("Students detail view has been debugged")
    logger.info("Logger of students detail view informs you!")
    logger.warning("Logger of students detail view warns you!")
    logger.error("Students detail view went wrong!")
    context = super(StudentDetailView, self).get_context_data(**kwargs)
    return context

class StudentListView(ListView):
  model = Student  
  paginate_by = 2 

  def get_queryset(self):
    id = self.request.GET.get('course_id',None)  
    if id:
      students = Student.objects.filter(courses=id)
      
    else:
      students = Student.objects.all()
    return students

  def get_context_data(self, **kwargs):
    context = super(StudentListView, self).get_context_data(**kwargs)
    id = self.request.GET.get('course_id',None) 
    if id:
      context['course_url'] = 'course_id=%s&' % id
    return context


#CreateView, UpdateView, DeleteView
class StudentCreateView(CreateView):
  model = Student
  
  def get_context_data(self, **kwargs):
    context = super(StudentCreateView, self).get_context_data(**kwargs)
    context['title'] = 'Student registration'
    return context

  def form_valid(self,form):
    form.save()
    messages.success(self.request, 'Student %s %s has been successfully added.' % (form.cleaned_data['name'], form.cleaned_data['surname']))
    return super(StudentCreateView, self).form_valid(form)

class StudentDeleteView(DeleteView):
  model = Student
  success_url = reverse_lazy('students:list_view')
  
  def delete(self, request, *args, **kwargs):
    student = self.get_object()
    messages.success(self.request, 'Info on %s %s has been sucessfully deleted.' % (student.name, student.surname))
    return super(StudentDeleteView, self).delete(request, *args, **kwargs)
  

  def get_context_data(self, **kwargs):
    context = super(StudentDeleteView, self).get_context_data(**kwargs)
    student =  Student.objects.get(id=self.kwargs['pk'])
    context['title'] = 'Student info suppression'
    context['message'] ='%s %s' % (student.name, student.surname)    
    return context
    

class StudentUpdateView(UpdateView):
  model = Student
  form_class = StudentModelForm
  success_url = reverse_lazy('students:list_view')
  

  def get_context_data(self, **kwargs):
    context = super(StudentUpdateView, self).get_context_data(**kwargs)    
    context['title'] = 'Student info update'
    return context

  def form_valid(self,form):
    student = form.save()
    messages.success(self.request, u'Info on %s %s the student has been sucessfully changed.'  % (student.name, student.surname))
    return super(StudentUpdateView, self).form_valid(form)

templates/students/add.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}ITBursa добавление студента{% endblock title %}


{% block stud_active %}active{% endblock stud_active %}


{% block content %}
<div class="jumbotron">
  <div class="container">
    <div class="col-md-12">
      <h3>Добавление нового студента</h3>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Добавить">
      </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/students/detail.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}ITBursa информация о студенте{% endblock title %}


{% block stud_active %}active{% endblock stud_active %}


{% block content %}
    <div class="jumbotron">
      <div class="container">
      <div class="col-md-12">
      
        <h1>{{ stud.name }} {{ stud.surname }}</h1>        
      </div>
      <div class="row">
        <div class="col-md-6">
          <table class="table tbl">
           <tbody>
             <tr class="pod">
                <td class="tbl">дата рождения</td>
                <td class="tbl">{{ stud.date_of_birth }}</td>
              </tr>
              <tr class="pod" >
                <td class="tbl">адрес</td>
                <td class="tbl">{{ stud.address }}</td>
              </tr>
              <tr class="pod" >
                <td class="tbl">почта</td>
                <td class="tbl">{{ stud.email }}</td>
              </tr>
              <tr class="pod" >
                <td class="tbl">логин skype</td>
                <td class="tbl">{{ stud.skype }}</td>
              </tr>
              <tr>
                <td class="tbl">телефон</td>
                <td class="tbl">{{ stud.phone }}</td>
              </tr>
              
              <tr class="pod" >
                <td class="tbl">курсы</td>
                <td>
                 {% for course in stud.courses_id %}
                  <a href="{% url 'courses:detail' course.id %}">{{ course  }}</a>
                  {% endfor %}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/students/edit.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}{{title}}{% endblock title %}


{% block stud_active %}active{% endblock stud_active %}


{% block content %}
<div class="jumbotron">
  <div class="container">
    <div class="col-md-12">
      <h3>Изменение профиля студента</h3>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Изменить">
      </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/students/list.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}ITBursa информация о студенте{% endblock title %}


{% block stud_active %}active{% endblock stud_active %}


{% block content %}
    <div class="jumbotron">
      <div class="container">

          <div class="page-header"><h3>Список студентов</h3></div>

      </div>
      <div class="row">
        <div class="col-md-12">
        {% if messages %}
        <div class="alert alert-success" role="alert">
          {% for message in messages %}
            {{ message }}
          {% endfor %}
        </div>
        {% endif %}
        <a href="{% url 'students:add' %}"><button class="glyphicon glyphicon-plus btn btn-success">Добавить пользователя</button></a>
          <table class="table">
            <thead>
              <tr>
                <th class="panel-heading">#</th>
                <th class="panel-heading">Фамилия и имя</th>
                <th class="panel-heading">Адрес</th>
                <th class="panel-heading">skype</th>
                <th class="panel-heading">Курсы</th>
                <th class="panel-heading"></th>
              </tr>
            </thead>
            <tbody>
            {% for student in students %}
              <tr>
                <td class="first">{{ student.id }}</td>
                <td class="tdfunc"><a href="{% url 'students:detail' student.id %}">{{ student.name }} {{ student.surname }}</a></td>
                <td class="tdfunc">{{ student.address }}</td>
                <td class="tdfunc">{{ student.skype }}</td>
                <td> {% for s_courses in student.courses.all%}
                  <a href="{% url 'courses:detail' s_courses.id %}">{{ s_courses  }}</a>
                  {% endfor %}
                </td>
                <td>
                  <a href="{% url 'students:edit' student.id %}">
                    <button class="glyphicon glyphicon-pencil btn btn-success">Изменить</button>
                  </a>
                </td>
                <td>
                  <a href="{% url 'students:remove' student.id %}">
                    <button class="glyphicon glyphicon-remove btn btn-success">Удалить</button>
                  </a>
                </td>
              </tr>
            {% endfor %}

            </tbody>
          </table>



<nav>
  <ul class="pagination">
   {% if page_obj.has_previous %}
    <li>
      <a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% endif %}

    {% if page_obj.has_next %}
    <li>
      <a href="?page={{ page_obj.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
        </div>
      </div>
    </div>
{% endblock content %}

templates/students/remove.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}ITBursa добавление студента{% endblock title %}


{% block stud_active %}active{% endblock stud_active %}


{% block content %}
<div class="jumbotron">
  <div class="container">
    <div class="col-md-12">
      <h3>Студент {{ message }} будет удален.</h3>
      <form method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
      </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/students/student_confirm_delete.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}{{title}}{% endblock title %}


{% block stud_active %}active{% endblock stud_active %}


{% block content %}
<div class="jumbotron">
  <div class="container">
    <div class="col-md-12">
    <h1>{{title}}</h1>
      <h3>Студент {{ message }} будет удален.</h3>
      <form method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
      </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/students/student_detail.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}{{ student.name }} {{ student.surname }} Details{% endblock title %}


{% block stud_active %}active{% endblock stud_active %}


{% block content %}
    <div class="jumbotron">
      <div class="container">
      <div class="col-md-12">
      
        <h1>{{ student.name }} {{ student.surname }}</h1>        
      </div>
      <div class="row">
        <div class="col-md-6">
          <table class="table tbl">
           <tbody>
             <tr class="pod">
                <td class="tbl">дата рождения</td>
                <td class="tbl">{{ student.date_of_birth }}</td>
              </tr>
              <tr class="pod" >
                <td class="tbl">адрес</td>
                <td class="tbl">{{ student.address }}</td>
              </tr>
              <tr class="pod" >
                <td class="tbl">почта</td>
                <td class="tbl">{{ student.email }}</td>
              </tr>
              <tr class="pod" >
                <td class="tbl">логин skype</td>
                <td class="tbl">{{ student.skype }}</td>
              </tr>
              <tr>
                <td class="tbl">телефон</td>
                <td class="tbl">{{ student.phone }}</td>
              </tr>
              
              <tr class="pod" >
                <td class="tbl">курсы</td>
                <td>
                {% for course in student.courses.all %}               
                <a href="{% url 'courses:detail' course.id %}">{{ course }}
                {% endfor %}
                
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

templates/students/student_form.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}{{ title }}{% endblock title %}


{% block stud_active %}active{% endblock stud_active %}


{% block content %}

<div class="jumbotron">
  <div class="container">
    <div class="col-md-12">
      <h3>{{ title }}</h3>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Добавить">
      </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/students/student_list.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}ITBursa информация о студенте{% endblock title %}


{% block stud_active %}active{% endblock stud_active %}


{% block content %}
    <div class="jumbotron">
      <div class="container">
        <div class="page-header">
          <h3>Список студентов</h3>
        </div>
      </div>
      <div class="row">
        <div class="col-md-8">
        {% if messages %}
        <div class="alert alert-success" role="alert">
          {% for message in messages %}
            {{ message }}
          {% endfor %}
        </div>
        {% endif %}
        <a href="{% url 'students:add' %}"><button class="glyphicon glyphicon-plus btn btn-success">Добавить пользователя</button></a>
          <table class="table table-hover">
            <thead>
              <tr>
                <th class="panel-heading">#</th>
                <th class="panel-heading">Фамилия и имя</th>
                <th class="panel-heading">Адрес</th>
                <th class="panel-heading">skype</th>
                <th class="panel-heading">Курсы</th>
                <th class="panel-heading"></th>
              </tr>
            </thead>
            <tbody>
            {% for student in student_list %}
              <tr>
                <td class="first">{{ student.id }}</td>
                <td class="tdfunc"><a href="{% url 'students:detail' student.id %}">{{ student.name }} {{ student.surname }}</a></td>
                <td class="tdfunc">{{ student.address }}</td>
                <td class="tdfunc">{{ student.skype }}</td>
                <td> {% for s_courses in student.courses.all%}
                  <a href="{% url 'courses:detail' s_courses.id %}">{{ s_courses  }}</a>
                  {% endfor %}
                </td>
                <td>
                  <a href="{% url 'students:edit' student.id %}">
                    <button class="glyphicon glyphicon-pencil btn btn-success">Изменить</button>
                  </a>
                </td>
                <td>
                  <a href="{% url 'students:remove' student.id %}">
                    <button class="glyphicon glyphicon-remove btn btn-success">Удалить</button>
                  </a>
                </td>
              </tr>
            {% endfor %}

            </tbody>
          </table>



<nav>
<ul class="pagination">
   {% if  is_paginated %}
    <!--Если есть предыдущая страница - то делаю ссылку "назад"-->
    {% if  page_obj.has_previous %}
      <li><a href="?{{course_url}}page={{ page_obj.previous_page_number }}"><< previous</a></li>
    {% endif %}
     {% for num in page_obj.paginator.page_range %}
        {% if num == page_obj.number %}
        <li><a><span class="active"><b>{{ num }}</b></span></a></li>
        {% else %}
        <li><a href="?{{course_url}}page={{ num }}"> {{ num }}</a></li>
        {% endif %}
    {% endfor %}

    <!--Если есть следующая страница - то ссылка "вперед"-->
    {% if  page_obj.has_next %}
     <li><a href="?{{course_url}}page={{ page_obj.next_page_number }}">next >></a></li>
    {% endif %}
  {% endif %}
  </ul>
</nav>

        </div>
      </div>
    </div>
{% endblock content %}