courses/urls.py
from django.conf.urls import patterns, url

from courses import views

urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)/$', views.CourseDetailView.as_view(), name='detail'),
    url(r'^add/$', views.CourseCreateView.as_view(), name='add'),
    url(r'^remove/(?P<pk>\d+)/$', views.CourseDeleteView.as_view(), name='remove'),
    url(r'^edit/(?P<pk>\d+)/$', views.CourseUpdateView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/add_lesson$', views.AddLessonCreateView.as_view(), name='add_lesson'),
    
)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)

pybursa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from pybursa import views
from django.views.generic import TemplateView
from feedbacks.views import FeedbackView



urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(),name='index'),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^students/', include('students.urls', namespace='students')),
    url(r'^contact/', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^quadratic/',include('quadratic.urls')),
    url(r'^coaches/',include('coaches.urls',namespace='coaches')),
    url(r'^feedback/', FeedbackView.as_view(), name = "feedback"),
)

students/urls.py
from django.conf.urls import patterns, url
from students import views

urlpatterns = patterns('',
    url(r'^$', views.StudentListView.as_view(), name='list_view'),
    url(r'^(?P<pk>\d+)/$', views.StudentDetailView.as_view(), name='detail'),
    url(r'^add/$', views.StudentCreateView.as_view(), name='add'),
    url(r'^remove/(?P<pk>\d+)/$', views.StudentDeleteView.as_view(), name='remove'),
    url(r'^edit/(?P<pk>\d+)/$', views.StudentUpdateView.as_view(), name='edit'),
)

feedbacks/models.py
from django.db import models

class Feedback(models.Model):
  name = models.CharField( max_length=255)
  subject = models.CharField(max_length=255)
  message = models.TextField()
  from_email = models.EmailField()
  create_date = models.DateTimeField (auto_now_add=True)

feedbacks/forms.py
# -*- coding: utf-8 -*-
from django import forms
from feedbacks.models import Feedback


class FeedbackForm(forms.ModelForm):
  class Meta:
    model = Feedback
    exclude = ['create_date']

feedbacks/views.py
from django.shortcuts import render
from django.contrib import messages
from django.views.generic.edit import CreateView
from feedbacks.models  import Feedback
from feedbacks.forms import FeedbackForm
from django.core.urlresolvers import reverse_lazy
from django.core.mail import mail_admins

class FeedbackView(CreateView):
  model = Feedback
  template_name = 'feedback.html'
  form_class = FeedbackForm
  success_url = reverse_lazy('feedback')

  def get_context_data(self, **kwargs):
    context = super(FeedbackView, self).get_context_data(**kwargs)
    context['title'] = 'Sending feedback'
    return context

  def form_valid(self, form):
    form.save()
    data = form.cleaned_data
    
    mail_admins(data['subject'], data['message'], fail_silently=True)
    messages.success(self.request, 'Thank you for your feedback! We will keep in touch with you very soon!')
    return super(FeedbackView, self).form_valid(form)


# Create your views here.

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>{% block title %}{% endblock title %}</title>
  <!-- Bootstrap -->

  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body role="document">
  <!-- Fixed navbar -->
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'index' %}">
          <img class="logo" alt="Logo" src="{% static 'images/logo.png' %}">
        </a>
      </div>
      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li  class="{% block index_active %}{% endblock index_active %}"><a href="{% url 'index' %}">Main</a></li>
          <li  class="{% block contact_active %}{% endblock contact_active %}"><a href="{% url 'contact' %}">Contacts</a></li>
          <li  class="{% block stud_active %}{% endblock stud_active %}"><a href="{% block students %}{% url 'students:list_view' %}{% endblock %}">Students</a></li>
          <li  class="{% block feedback %}{% endblock %}"><a href="{% url 'feedback' %}">Feedback</a></li>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </nav>
  <div class="container theme-showcase" role="main">
    <!-- Main jumbotron for a primary marketing message or call to action -->
    {% block content %}{% endblock content %}
  </div>
  <div class="panel-footer newfooter">
    <span class="firma">IT Bursa</span>. <span id="prava">PyBursa|RubyBursa|JavaBursa|BasicBursa</span>
  </div>

  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <!-- Include all compiled plugins (below), or include individual files as needed -->
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>

templates/contact.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}ITBursa Контакты{% endblock title %}


{% block contact_active %}active{% endblock contact_active %}


  {% block content %}
    <div class="jumbotron">
      <div class="col-sm-4">
        <h1>Director</h1>
        <p>
          Name: <span class="name">Иванов Сергей Петрович</span>
          <br> Skype:
          <span class="skype">petrovicj1</span>
          <br>
          <u class="courses">Email:petrovicj1@gmail.com</u>
          <br> Phone:
          <span class="phone">066-504-5038</span>
          <br>
        </p>
      </div>
      <div class="col-sm-4">
        <img class="photo" src="{% static 'images/screenshot-hameleons.com 2015-12-22 21-05-50.png' %}" id="dir">
      </div>
      <div class="col-sm-4">
        <h1>Founder</h1>
        <p>
          Name: <span class="name">Аксенова Татьяна Ивановна</span>
          <br> Skype:
          <span class="skype">aksenova3</span>
          <br> Email:aksenova3@gmail.com
          <br> Phone:
          <span class="phone">066-504-50-38</span>
          <br>
        </p>
      </div>
      <div class="col-sm-4">
        <img class="photo" src="{% static 'images/screenshot-hameleons.com 2015-12-22 21-06-00.png' %}" id="manager">
      </div>
      <div>
        <h1>Manager</h1>
        <p>
          Name: <span class="name">Смирнов Николай</span>
          <br> Skype:
          <span class="skype">smairnov</span>
          <br> Email:smairnov@gmail.com
          <br> Phone:
          <span class="phone">066-504-50-38</span>
          <br>
        </p>
      </div>
    </div>
  {% endblock content %}

templates/feedback.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}{{ title }}{% endblock title %}


{% block feedback %}active{% endblock %}


{% block content %}

<div class="jumbotron">
{% if messages %}
        <div class="alert alert-success" role="alert">
          {% for message in messages %}
            {{ message }}
          {% endfor %}
        </div>
        {% endif %}  
  <div class="container">
    <div class="col-md-12">
      <h3>{{ title }}</h3>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Отправить">
      </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/index.html
{% extends "base.html" %}


{% load staticfiles %}


{% block index_active %}active{% endblock index_active %}


{% block title %}ITBursa Главная{% endblock title %}


{% block content %}
    <div class="jumbotron">
    {% if messages %}
        <div class="alert alert-success" role="alert">
          {% for message in messages %}
            {{ message }}
          {% endfor %}
        </div>
        {% endif %}
      <div class="container">

        <h1>Description</h1>
        <div class="page-header"><h2>PyBursa - курсы Python/Django</h2></div>
      </div>
      <p>
        Курсы ItBursa начали работу в 2014 году. Мы специализируемся на «модных»
        языках программирования. Принципиальное наше отличие от других курсов –
        максимум практики и жесткая система обязательных домашних заданий.
        Преподаватели – опытные практикующие разработчики, они помогают
        участникам в ходе курсов создать реальные проекты и получить
        практические навыки, применимые к работе. Домашние задания на наших
        курсах обязательны и их невыполнение приводит к исключению с курсов.
        Таким образом, мы готовим не просто «слушателей» курсов, а настоящих специалистов,
        способных создавать пусть простые, но рабочие проекты.
      </p>
      <div class="jumbotron">
        <div class="container">
          <h3>Выбирай любой курс, на котором хочешь учиться или предложи свой!</h3>
        </div>
         <a href="{% url 'courses:add' %}"><button class="glyphicon glyphicon-plus btn btn-success">Добавить курс</button></a>
      </div>
      <div class="row">

        <div class="col-md-8">
          <table class="table table-hover">
            <thead>
              <tr>
                <th class="panel-heading">Курс</th>
                <th class="panel-heading">Описание</th>
                <th class="panel-heading"></th>
              </tr>
            </thead>
            <tbody>
            {% for c in course %}
              <tr>
              <td class="tdfunc"><a href="{% url 'courses:detail' c.id %} ">{{ c|title }}</a></td>
                <td>
                  {{ c.short_description|title }}
                </td>
                <td>
                  <a href="{% url 'courses:edit' c.id %}">
                    <button class="glyphicon glyphicon-pencil btn btn-success">Изменить</button>
                  </a>
                </td>
                <td>
                  <a href="{% url 'courses:remove' c.id %}">
                    <button class="glyphicon glyphicon-remove btn btn-success">Удалить</button>
                  </a>
                </td>
              </tr>

            {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
{% endblock content %}

templates/results.html
<h1>Решение квадратного уравнения</h1>
  <form>
    {{form.as_p}}
    <input type="submit">
  </form>
D  = {{ d }}
x1 = {{ x1 }}
x2 = {{ x2 }}

templates/student_detail.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}ITBursa информация о студенте{% endblock title %}
{% block stud_active %}active{% endblock %}
{% block content %}
<div class="jumbotron">
      <div class="container">
      <div class="col-md-12">
        <h1>Рожков Павел</h1>
        <div class="col-md-8">
        <img class="avatar" src="{% static 'images/student_avatar.png' %}">
        </div>
        <div class="col-md-8">
        <button type="button" class="btn btn-lg btn-success btn-o-sebe">Студент о себе</button>
        <h3>Student's cards</h3>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <table class="table tbl">
           <tbody>
              <tr class="pod">
                <td class="tbl">Surname</td>
                <td class="tbl">Рожков</td>
              </tr>
              <tr class="pod" >
                <td class="tbl">Name</td>
                <td class="tbl">Павел</td>
              </tr>
              <tr class="pod" >
                <td class="tbl">Patronymic</td>
                <td class="tbl">Геннадиевич</td>
              </tr>
              <tr  class="pod">
                <td class="tbl">Birth Date</td>
                <td class="tbl">26.02.1994</td>
              </tr>
              <tr class="pod" >
                <td class="tbl">Address</td>
                <td class="tbl">г. Усть-Джегута, ул. Бауманская, дом 34, квартира 48</td>
              </tr>
              <tr class="pod" >
                <td class="tbl">E-mail</td>
                <td class="tbl">tayskiyostap287@gmail.com</td>
              </tr>
              <tr class="pod" >
                <td class="tbl">Skype</td>
                <td class="tbl">TayskiyOstap287</td>
              </tr>
              <tr  class="pod">
                <td class="tbl">Package</td>
                <td class="tbl">Standart</td>
              </tr>
              <tr class="pod" >
                <td class="tbl">Average Grade</td>
                <td class="tbl">100%</td>
              </tr>
              <tr  class="pod">
                <td class="tbl">Ratingv</td>
                <td class="tbl">1</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div class="col-md-6">
          <table class="table tbl">
      
           <tbody>
           <tr  class="pod">
              <td class="tbl">Course</td>
              <td class="tbl">Week</td>
              <td class="tbl">Control type</td>
              <td class="tbl">Grade</td>
            </tr>
              <tr >
                <td class="tbl" rowspan="4">Python Введение</td>
                <td class="tbl" rowspan="2">Week1</td>
                <td class="tbl">Tests</td>
                <td class="tbl">100</td>
              </tr>
              <tr >                
                <td class="tbl">Problem Task 1</td>
                <td class="tbl">100</td>
              </tr>
              <tr >              
                <td class="tbl" rowspan="2">Week2</td>  
                <td class="tbl">Tests</td>
                <td class="tbl">100</td>
              </tr> 
              <tr >                
                <td class="tbl">Problem Task 2</td>
                <td class="tbl">100</td>
              </tr>
            </tbody>
          </table>
        </div>

      </div>
    </div>
  </div>  
{% endblock content %}

templates/student_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}ITBursa Студенты{% endblock title %}
{% block stud_active %}active{% endblock %}
    {% block content %}
    <div class="jumbotron">
      <div class="container">
        <h1>Студенты курса: PyBursa</h1>
      </div>
      <div class="row">
        <div class="col-md-12">
          <table class="table">
            <thead>
              <tr>
                <th>No</th>
                <th>Surname</th>
                <th>Name</th>
                <th>Address</th>
                <th>Skype</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><a href="{% url 'student_detail' %}">1</a></td>
                <td>Рожков</td>
                <td>Павел</td>
                <td>г. Фурманов, ул. Академическая, дом 27, квартира 13</td>
                <td>RusinFilipp336</td>
              </tr>
              <tr>
                <td>2</td>
                <td>Яковлева</td>
                <td>Харитина</td>
                <td>г. Холмогоры, ул. Маршала Конева, дом 89, квартира 134</td>
                <td>YakovlevaHaritina114</td>
              </tr>
              <tr>
                <td>3</td>
                <td>Недашковский</td>
                <td>Вячеслав</td>
                <td>г. Фрунзенское, ул. Гвардейская, дом 20, квартира 170</td>
                <td>NedashkovskiyVyacheslav165</td>
              </tr>
              <tr>
                <td>4</td>
                <td>Кудрявцева</td>
                <td>Элиза</td>
                <td>г. Усть-Калманка, ул. Железнодорожников, дом 42, квартира 180</td>
                <td>KudryavtsevaEliza213</td>
              </tr>
              <tr>
                <td>5</td>
                <td>Тайский</td>
                <td>Остап</td>
                <td>г. Усть-Джегута, ул. Бауманская, дом 34, квартира 48</td>
                <td>TayskiyOstap287</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
    {% endblock content %}
  