courses/urls.py
from django.conf.urls import patterns, url

from courses import views

urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)/$', views.CourseDetailView.as_view(), name='detail'),
    url(r'^add/$', views.CourseCreateView.as_view(), name='add'),
    url(r'^remove/(?P<pk>\d+)/$', views.CourseDeleteView.as_view(), name='remove'),
    url(r'^edit/(?P<pk>\d+)/$', views.CourseUpdateView.as_view(), name='edit'),
    url(r'^(?P<pk>\d+)/add_lesson$', views.AddLessonCreateView.as_view(), name='add_lesson'),
    
)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)

pybursa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from pybursa import views
from django.views.generic import TemplateView
from feedbacks.views import FeedbackView



urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(),name='index'),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^students/', include('students.urls', namespace='students')),
    url(r'^contact/', TemplateView.as_view(template_name='contact.html'), name='contact'),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^quadratic/',include('quadratic.urls')),
    url(r'^coaches/',include('coaches.urls',namespace='coaches')),
    url(r'^feedback/', FeedbackView.as_view(), name = "feedback"),
)

students/urls.py
from django.conf.urls import patterns, url
from students import views

urlpatterns = patterns('',
    url(r'^$', views.StudentListView.as_view(), name='list_view'),
    url(r'^(?P<pk>\d+)/$', views.StudentDetailView.as_view(), name='detail'),
    url(r'^add/$', views.StudentCreateView.as_view(), name='add'),
    url(r'^remove/(?P<pk>\d+)/$', views.StudentDeleteView.as_view(), name='remove'),
    url(r'^edit/(?P<pk>\d+)/$', views.StudentUpdateView.as_view(), name='edit'),
)

courses/models.py
from django.db import models
from coaches.models import Coach
from django.core.urlresolvers import reverse

class Course(models.Model):
  name = models.CharField(verbose_name=u'Name of course', max_length = 255)
  short_description = models.CharField(max_length = 255)
  description = models.TextField()
  coach = models.ForeignKey(Coach, blank=True, null=True, related_name="coach_courses")
  assistant = models.ForeignKey(Coach, blank=True, null=True, related_name="assistant_courses")
  
  def __unicode__(self):
    return self.name

class Lesson(models.Model):
  subject = models.CharField(max_length = 255)
  description = models.TextField()
  course = models.ForeignKey(Course) 
  order = models.PositiveIntegerField()

  def __unicode__(self):
    return self.subject

courses/forms.py
# -*- coding: utf-8 -*-
from django import forms
from courses.models import Course,Lesson


class CourseModelForm(forms.ModelForm):
  class Meta:
    model = Course

class LessonModelForm(forms.ModelForm):
  class Meta:
    model = Lesson

courses/views.py
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render,redirect, get_object_or_404
from courses.models import Lesson,Course
from coaches.models import Coach
from courses.forms import CourseModelForm, LessonModelForm
from django.contrib import messages
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import FormView, CreateView, UpdateView, DeleteView
import logging
logger = logging.getLogger(__name__)



class CourseDetailView(DetailView):
  model = Course
  template_name = "courses/detail.html"
  context_object_name = 'course'
  fields = '__all__'

  

  def get_context_data(self, **kwargs):
    logger.debug("Courses detail view has been debugged")
    logger.info("Logger of courses detail view informs you!")
    logger.warning("Logger of courses detail view warns you!")
    logger.error("Courses detail view went wrong!")
    context = super(CourseDetailView, self).get_context_data(**kwargs)
    lessons = Lesson.objects.filter(course=self.object)
    context['lessons'] = lessons
    return context 

class CourseCreateView(CreateView):
  model = Course
  context_object_name = 'course'
  template_name = 'courses/add.html'
  success_url = reverse_lazy('index')

  def get_context_data(self, **kwargs):
    context = super(CourseCreateView, self).get_context_data(**kwargs)
    context['title'] = 'Course creation'
    return context 

  def form_valid(self,form):
    form.save()
    messages.success(self.request, 'Course %s has been successfully added.' % (form.cleaned_data['name']))
    return super(CourseCreateView, self).form_valid(form)

class CourseDeleteView(DeleteView):
  model = Course
  success_url = reverse_lazy('index')
  context_object_name = 'course'
  template_name = 'courses/remove.html'

  def delete(self, request, *args, **kwargs):
    course = self.get_object()
    messages.success(self.request, 'Course %s has been deleted.' % (course.name))
    return super(CourseDeleteView, self).delete(request, *args, **kwargs)
  
  def get_context_data(self, **kwargs):
    context = super(CourseDeleteView, self).get_context_data(**kwargs)
    course =  Course.objects.get(id=self.kwargs['pk'])
    context['title'] = 'Course deletion'
    return context


class CourseUpdateView(UpdateView):
  model = Course
  success_url = reverse_lazy('index')
  context_object_name = 'course'
  template_name = 'courses/edit.html' 
  fields = '__all__'
   

  def get_context_data(self, **kwargs):
      context = super(CourseUpdateView, self).get_context_data(**kwargs)
      context['title'] = 'Course update'
      return context

  def form_valid(self,form):
    course = form.save()
    messages.success(self.request, u"The changes have been saved.")
    return super(CourseUpdateView, self).form_valid(form)

  def get_success_url(self):
    return reverse_lazy('courses:edit', None, [self.object.id])

class AddLessonCreateView(CreateView):
  model = Lesson
  context_object_name = 'lesson'
  template_name = 'courses/add_lesson.html'


  def get_context_data(self, **kwargs):
      context = super(AddLessonCreateView, self).get_context_data(**kwargs)
      context['title'] = 'Add Lesson'
      return context

  def get_initial(self):
    return {'course':self.kwargs['pk']} 

  def form_valid(self,form):
    form.save()
    messages.success(self.request, 'Lesson %s has been successfully added.' % (form.cleaned_data['subject']))
    return super(AddLessonCreateView, self).form_valid(form)

  def get_success_url(self):    
    return  reverse_lazy('courses:detail', None, [self.object.course_id])

templates/courses/add.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}ITBursa новый курс{% endblock title %}


{% block stud_active %}active{% endblock stud_active %}


{% block content %}
<div class="jumbotron">
  <div class="container">
    <div class="col-md-12">
      <h3>{{title}}</h3>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Добавить">
      </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/courses/add_lesson.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}ITBursa новый курс{% endblock title %}


{% block stud_active %}active{% endblock stud_active %}


{% block content %}
<div class="jumbotron">
  <div class="container">
    <div class="col-md-12">
      <h3>Добавление нового урока</h3>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Добавить">
      </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/courses/detail.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}ITBursa информация о курсе{% endblock title %}


{% block stud_active %}active{% endblock stud_active %}
{% block students %}{% url 'students:list_view' %}?course_id={{course.id}}{% endblock %}

{% block content %}    
<div class="jumbotron">
{% if messages %}
        <div class="alert alert-success" role="alert">
          {% for message in messages %}
            {{ message }}
          {% endfor %}
        </div>
        {% endif %}  

    <div class="container">
        <div class="col-md-12">
            <h1>{{ course }}</h1>
            <h3>{{ course.description|truncatechars:32 }}</h3>
        </div>
    </div>      
      {% include "include/coach_include.html" with block_title="Преподаватель" instructor=course.coach %}            
      {% include "include/coach_include.html" with block_title="Ассистент" instructor=course.assistant %}
      <a href="{% url 'courses:add_lesson' course.id %}"><button class="glyphicon glyphicon-plus btn btn-success">Добавить занятие</button></a>      
    <div class="row">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th class="panel-heading">#</th>
                        <th class="panel-heading">Тема</th>
                        <th class="panel-heading">Описание</th>
                    </tr>
                </thead>
                <tbody>
            {% for c in lessons %}
              
                    <tr>
                        <td class="first">{{ c.order }}</td>
                        <td class="tdfunc">{{ c }}</td>
                        <td>{{ c.description }}</td>
                    </tr>
            {% endfor %}
           
            
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

templates/courses/edit.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}ITBursa изменение курса{% endblock title %}


{% block stud_active %}active{% endblock stud_active %}


{% block content %}
<div class="jumbotron">
  <div class="container">
  <h3>{{title}}</h3>
  {% if messages %}
        <div class="alert alert-success" role="alert">
          {% for message in messages %}
            {{ message }}
          {% endfor %}
        </div>
        {% endif %}
    <div class="col-md-12">

      <h3>Изменение курса</h3>
      <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Изменить">
      </form>
    </div>
  </div>
</div>
{% endblock content %}

templates/courses/remove.html
{% extends "base.html" %}


{% load staticfiles %}


{% block title %}ITBursa добавление студента{% endblock title %}


{% block stud_active %}active{% endblock stud_active %}


{% block content %}
<div class="jumbotron">
  <div class="container">
    <div class="col-md-12">
    <h1>{{title}}</h1>
      <h3>Курс {{ course.name }} будет удален.</h3>
      <form method="post">
        {% csrf_token %}
        <input type="submit" value="Удалить">
      </form>
    </div>
  </div>
</div>
{% endblock content %}